resources:
- name: cloud-chaos.git
  type: git
  source:
    uri: https://github.com/govau/cloud-chaos.git
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
jobs:
- name: chaos-in-development
  serial: true
  plan:
  - do:
    - get: cloud-chaos.git
      trigger: true
    - put: slack
      params:
        text: |
          :chaos: $BUILD_JOB_NAME started
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    - task: chaos-development-gorouter
      file: cloud-chaos.git/ci/run-experiment.yml
      params:
        AWS_ACCESS_KEY_ID: ((aws-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
        AWS_REGION: ap-southeast-2
        AWS_ASSUME_ROLE_ARN: ((dev-aws-assume-role-arn))
        ENV_NAME: ((dev-env-name))
        EXPERIMENT: kill-go-router
    on_failure:
      put: slack
      params:
        text: |
          :x: :chaos: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_success:
      put: slack
      params:
        text: |
          :tada: :chaos: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
